version: '2'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql-springkafka
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: springkafka
      MYSQL_PASSWORD: springkafka
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springkafka

  jaeger:
    image: jaegertracing/all-in-one:1.26
    container_name: jaeger-springkafka
    ports:
      - 6831:6831/udp
      - 5775:5775/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411

  kafka-cluster:
    image: landoop/fast-data-dev:latest
    environment:
      ADV_HOST: 127.0.0.1         # Change to 192.168.99.100 if using Docker Toolbox
      RUNTESTS: 0                 # Disable Running tests so the cluster starts faster
      FORWARDLOGS: 0              # Disable running 5 file source connectors that bring application logs into Kafka topics
      SAMPLEDATA: 0               # Do not create sea_vessel_position_reports, nyc_yellow_taxi_trip_data, reddit_posts topics with sample Avro records.
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker




